# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [3]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv')
pd.set_option('display.max_columns', None)
df.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,Location Code,Marital Status,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,48029,Suburban,Married,61,7.0,52,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,0,Suburban,Single,64,3.0,26,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,22139,Suburban,Single,100,34.0,31,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,49078,Suburban,Single,97,10.0,3,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,23675,Suburban,Married,117,NaN,31,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [2]:
df.shape

(10910, 26)

In [ ]:
df.info() #para tener visibilidad del nombre de las columnas.

<class 'pandas.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     10910 non-null  int64
 1   Customer                       10910 non-null  str
 2   State                          10279 non-null  str
 3   Customer Lifetime Value        10910 non-null  float64
 4   Response                       10279 non-null  str
 5   Coverage                       10910 non-null  str
 6   Education                      10910 non-null  str
 7   Effective To Date              10910 non-null  str
 8   EmploymentStatus               10910 non-null  str
 9   Gender                         10910 non-null  str
 10  Income                         10910 non-null  int64
 11  Location Code                  10910 non-null  str
 12  Marital Status                 10910 non-null  str
 13  Monthly Premium Auto           10910 non-null  int64
 14  Months Since Last Claim        10277 non-null  float64
 15  Months Since Policy Inception  10910 non-null  int64
 16  Number of Open Complaints      10277 non-null  float64
 17  Number of Policies             10910 non-null  int64
 18  Policy Type                    10910 non-null  str
 19  Policy                         10910 non-null  str
 20  Renew Offer Type               10910 non-null  str
 21  Sales Channel                  10910 non-null  str
 22  Total Claim Amount             10910 non-null  float64
 23  Vehicle Class                  10288 non-null  str
 24  Vehicle Size                   10288 non-null  str
 25  Vehicle Type                   5428 non-null   str
dtypes: float64(4), int64(5), str(17)
memory usage: 2.2 MB

In [5]:
df.columns = df.columns.str.lower().str.replace(' ', '_')   #vamos a corregir el nombre de las columnas para empezar con el analisis. 
df.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,location_code,marital_status,monthly_premium_auto,months_since_last_claim,months_since_policy_inception,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,48029,Suburban,Married,61,7.0,52,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,0,Suburban,Single,64,3.0,26,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,22139,Suburban,Single,100,34.0,31,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,49078,Suburban,Single,97,10.0,3,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,23675,Suburban,Married,117,NaN,31,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [ ]:
#1. Crear un dataframe con clientes que: tiene pocas reclamaciones (inferior a 1000) y han respondido Si a la campaña. Lo que tenemos que hacer es filtrar los datos. 

new_dataframe = df[(df['total_claim_amount'] < 1000) & (df['response'] == 'Yes')]
new_dataframe

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,location_code,marital_status,monthly_premium_auto,months_since_last_claim,months_since_policy_inception,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,49078,Suburban,Single,97,10.0,3,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,66839,Suburban,Single,154,33.0,24,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,79487,Suburban,Divorced,114,20.0,87,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,41479,Rural,Married,94,14.0,38,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,63774,Rural,Divorced,111,18.0,63,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10844,10844,FM31768,Arizona,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,57693,Suburban,Divorced,76,16.0,56,0.0,3,Personal Auto,Personal L1,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10852,10852,KZ80424,Washington,8382.478392,Yes,Basic,Bachelor,1/27/11,Employed,M,25998,Suburban,Married,71,16.0,38,0.0,2,Personal Auto,Personal L2,Offer2,Call Center,791.878042,NaN,NaN,A
10872,10872,XT67997,California,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,57693,Suburban,Divorced,76,16.0,56,0.0,3,Personal Auto,Personal L3,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10887,10887,BY78730,Oregon,8879.790017,Yes,Basic,High School or Below,2/3/11,Employed,F,52583,Urban,Single,113,12.0,59,0.0,7,Special Auto,Special L2,Offer1,Agent,528.200860,SUV,Small,A
10897,10897,MM70762,Arizona,9075.768214,Yes,Basic,Master,1/26/11,Employed,M,37722,Rural,Single,116,8.0,23,0.0,8,Personal Auto,Personal L1,Offer1,Agent,158.077504,Sports Car,Medsize,A

In [ ]:
#2. Calcular medias de monthly_premium y de customer_lifetime_value agrupado por: policy_type y gender considerando la response: yes y trabajando con el original dataframe y compararlo con total_claim_amount

yes_response = df[df['response'] == 'Yes']
yes_response

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,location_code,marital_status,monthly_premium_auto,months_since_last_claim,months_since_policy_inception,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,49078,Suburban,Single,97,10.0,3,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,66839,Suburban,Single,154,33.0,24,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,79487,Suburban,Divorced,114,20.0,87,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,41479,Rural,Married,94,14.0,38,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,63774,Rural,Divorced,111,18.0,63,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10844,10844,FM31768,Arizona,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,57693,Suburban,Divorced,76,16.0,56,0.0,3,Personal Auto,Personal L1,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10852,10852,KZ80424,Washington,8382.478392,Yes,Basic,Bachelor,1/27/11,Employed,M,25998,Suburban,Married,71,16.0,38,0.0,2,Personal Auto,Personal L2,Offer2,Call Center,791.878042,NaN,NaN,A
10872,10872,XT67997,California,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,57693,Suburban,Divorced,76,16.0,56,0.0,3,Personal Auto,Personal L3,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10887,10887,BY78730,Oregon,8879.790017,Yes,Basic,High School or Below,2/3/11,Employed,F,52583,Urban,Single,113,12.0,59,0.0,7,Special Auto,Special L2,Offer1,Agent,528.200860,SUV,Small,A
10897,10897,MM70762,Arizona,9075.768214,Yes,Basic,Master,1/26/11,Employed,M,37722,Rural,Single,116,8.0,23,0.0,8,Personal Auto,Personal L1,Offer1,Agent,158.077504,Sports Car,Medsize,A

In [22]:
customer_lifetime_mean = yes_response.groupby(['policy_type', 'gender'])['customer_lifetime_value'].mean()
customer_lifetime_mean

policy_type     gender
Corporate Auto  F         7712.628736
                M         7944.465414
Personal Auto   F         8339.791842
                M         7448.383281
Special Auto    F         7691.584111
                M         8247.088702
Name: customer_lifetime_value, dtype: float64

In [24]:
monthly_premium_auto_mean = yes_response.groupby(['policy_type', 'gender'])['monthly_premium_auto'].mean()
monthly_premium_auto_mean

policy_type     gender
Corporate Auto  F         94.301775
                M         92.188312
Personal Auto   F         98.998148
                M         91.085821
Special Auto    F         92.314286
                M         86.343750
Name: monthly_premium_auto, dtype: float64

In [23]:
total_claim_amount_mean = yes_response.groupby(['policy_type', 'gender'])['total_claim_amount'].mean()
total_claim_amount_mean

policy_type     gender
Corporate Auto  F         433.738499
                M         408.582459
Personal Auto   F         452.965929
                M         457.010178
Special Auto    F         453.280164
                M         429.527942
Name: total_claim_amount, dtype: float64

In [ ]:
mean_comparison = pd.concat([customer_lifetime_mean, monthly_premium_auto_mean, total_claim_amount_mean], axis=1)
mean_comparison.unstack()

                       customer_lifetime_value  monthly_premium_auto  \
policy_type    gender
Corporate Auto F                   7712.628736             94.301775
               M                   7944.465414             92.188312
Personal Auto  F                   8339.791842             98.998148
               M                   7448.383281             91.085821
Special Auto   F                   7691.584111             92.314286
               M                   8247.088702             86.343750

                       total_claim_amount
policy_type    gender
Corporate Auto F               433.738499
               M               408.582459
Personal Auto  F               452.965929
               M               457.010178
Special Auto   F               453.280164
               M               429.527942

Insights del analisis: 
- Las mujeres con pólizas Personal Auto son el segmento más rentable para la empresa.
- Hombres con pólizas Special Auto también representan clientes de alto valor.
- Personal auto policy es el grupo más arriesgado, ya que son los que generan más reclamaciones. 
- Vemos que el grupo de personal auto es muy rentable para la empresa pero con un riesgo a considerar.

In [30]:
#3. Analizar cuantos clientes hay por state que tienen poliza. Y filtra el resultado incluyendo solo aquellos states con mas de 500 paises. 

state_customers = df.groupby('state')['customer'].count()
state_customers

state
Arizona       1937
California    3552
Nevada         993
Oregon        2909
Washington     888
Name: customer, dtype: int64

In [32]:
filtered_states = state_customers[state_customers > 500]
filtered_states

state
Arizona       1937
California    3552
Nevada         993
Oregon        2909
Washington     888
Name: customer, dtype: int64

In [41]:
#4. Calcula el max, min, mediana de customer lifetime value por education level y gender. 

customer_lifetime_max = df.groupby(['education', 'gender'])['customer_lifetime_value'].agg('max')
customer_lifetime_max

education             gender
Bachelor              F         73225.95652
                      M         67907.27050
College               F         61850.18803
                      M         61134.68307
Doctor                F         44856.11397
                      M         32677.34284
High School or Below  F         55277.44589
                      M         83325.38119
Master                F         51016.06704
                      M         50568.25912
Name: customer_lifetime_value, dtype: float64

In [40]:
customer_lifetime_min = df.groupby(['education', 'gender'])['customer_lifetime_value'].agg('min')
customer_lifetime_min

education             gender
Bachelor              F         1904.000852
                      M         1898.007675
College               F         1898.683686
                      M         1918.119700
Doctor                F         2395.570000
                      M         2267.604038
High School or Below  F         2144.921535
                      M         1940.981221
Master                F         2417.777032
                      M         2272.307310
Name: customer_lifetime_value, dtype: float64

In [39]:
customer_lifetime_median = df.groupby(['education', 'gender'])['customer_lifetime_value'].agg('median')
customer_lifetime_median

education             gender
Bachelor              F         5640.505303
                      M         5548.031892
College               F         5623.611187
                      M         6005.847375
Doctor                F         5332.462694
                      M         5577.669457
High School or Below  F         6039.553187
                      M         6286.731006
Master                F         5729.855012
                      M         5579.099207
Name: customer_lifetime_value, dtype: float64

In [43]:
comparison_table = pd.concat([customer_lifetime_max, customer_lifetime_min, customer_lifetime_median], axis=1)
comparison_table.unstack().round(2)

                     customer_lifetime_value                              \
gender                                     F         M        F        M
education
Bachelor                            73225.96  67907.27  1904.00  1898.01
College                             61850.19  61134.68  1898.68  1918.12
Doctor                              44856.11  32677.34  2395.57  2267.60
High School or Below                55277.45  83325.38  2144.92  1940.98
Master                              51016.07  50568.26  2417.78  2272.31


gender                      F        M
education
Bachelor              5640.51  5548.03
College               5623.61  6005.85
Doctor                5332.46  5577.67
High School or Below  6039.55  6286.73
Master                5729.86  5579.10

Insights:
- Hay una gran diferencia entre el valor máximo y la mediana, lo que indica pocos clientes altamente valiosos. 
- Los clientes con menor nivel educativo pueden alcanzar valores de vida muy altos, lo que rompe la idea de que mayor educación implica mayor valor.
- El género no tiene un impacto consistente en el valor del cliente, ya que su efecto varía según el nivel educativo.